const data = {
  id: 1,
  name: '通用业务表单',
  comment: '通用业务表单',
  parentId: 0,
  sort: null,
  nodeType: 1,
  formId: null,
  indicatorNum: 0,
  child: [
    {
      id: 352,
      name: '测试排序',
      comment: '测试排序',
      parentId: 1,
      sort: null,
      nodeType: 1,
      formId: null,
      indicatorNum: 0,
      // child: null,
      indicatorVOList: null,
    },
    {
      id: 124,
      name: '未分类',
      comment: '未分类',
      parentId: 1,
      sort: null,
      nodeType: 1,
      formId: null,
      indicatorNum: 0,
      child: [
        {
          id: 370,
          name: '剔库规则表100',
          comment: '剔库规则表100',
          parentId: 124,
          sort: null,
          nodeType: 2,
          formId: 318,
          indicatorNum: 10,
          child: null,
          indicatorVOList: null,
        },
        {
          id: 366,
          name: '发票表',
          comment: null,
          parentId: 124,
          sort: null,
          nodeType: 2,
          formId: 314,
          indicatorNum: 2,
          child: null,
          indicatorVOList: null,
        },
        {
          id: 322,
          name: '纳税人基本信息表1',
          comment: '纳税人基本信息表1',
          parentId: 124,
          sort: null,
          nodeType: 2,
          formId: 282,
          indicatorNum: 42,
          child: null,
          indicatorVOList: null,
        },
      ],
      indicatorVOList: null,
    },
    {
      id: 142,
      name: '优惠信息',
      comment: '优惠信息',
      parentId: 1,
      sort: null,
      nodeType: 1,
      formId: null,
      indicatorNum: 0,
      child: [
        {
          id: 143,
          name: '优惠政策',
          comment: '优惠政策',
          parentId: 142,
          sort: null,
          nodeType: 1,
          formId: null,
          indicatorNum: 0,
          child: null,
          indicatorVOList: null,
        },
      ],
      indicatorVOList: null,
    },
    {
      id: 52,
      name: '出口退税',
      comment: '出口退税',
      parentId: 1,
      sort: null,
      nodeType: 1,
      formId: null,
      indicatorNum: 0,
      child: [
        {
          id: 374,
          name: '时间表测试单个抽数',
          comment: null,
          parentId: 52,
          sort: null,
          nodeType: 2,
          formId: 322,
          indicatorNum: 1,
          child: null,
          indicatorVOList: null,
        },
        {
          id: 371,
          name: '关联关系表0802',
          comment: null,
          parentId: 52,
          sort: null,
          nodeType: 2,
          formId: 319,
          indicatorNum: 2,
          child: null,
          indicatorVOList: null,
        },
        {
          id: 363,
          name: '企业年度关联业务往来报告表-报告企业信息表10',
          comment: null,
          parentId: 52,
          sort: null,
          nodeType: 2,
          formId: 311,
          indicatorNum: 2,
          child: null,
          indicatorVOList: null,
        },
        {
          id: 361,
          name: 'VB你1',
          comment: 'VB你1',
          parentId: 52,
          sort: null,
          nodeType: 2,
          formId: 310,
          indicatorNum: 4,
          child: null,
          indicatorVOList: null,
        },
      ],
      indicatorVOList: null,
    },
    {
      id: 51,
      name: '税务稽查',
      comment: '税务稽查',
      parentId: 1,
      sort: null,
      nodeType: 1,
      formId: null,
      indicatorNum: 0,
      child: [
        {
          id: 373,
          name: '无形资产所有权交易表',
          comment: null,
          parentId: 51,
          sort: null,
          nodeType: 2,
          formId: 321,
          indicatorNum: 7,
          child: null,
          indicatorVOList: null,
        },
        {
          id: 365,
          name: 'test20200801-无时间测试',
          comment: null,
          parentId: 51,
          sort: null,
          nodeType: 2,
          formId: 313,
          indicatorNum: 2,
          child: null,
          indicatorVOList: null,
        },
      ],
      indicatorVOList: null,
    },
    {
      id: 50,
      name: '违法违章',
      comment: '违法违章',
      parentId: 1,
      sort: null,
      nodeType: 1,
      formId: null,
      indicatorNum: 0,
      child: [
        {
          id: 369,
          name: '非时间抽数',
          comment: null,
          parentId: 50,
          sort: null,
          nodeType: 2,
          formId: 317,
          indicatorNum: 1,
          child: null,
          indicatorVOList: null,
        },
        {
          id: 360,
          name: '时间区间表',
          comment: null,
          parentId: 50,
          sort: null,
          nodeType: 2,
          formId: 309,
          indicatorNum: 13,
          child: null,
          indicatorVOList: null,
        },
      ],
      indicatorVOList: null,
    },
    {
      id: 48,
      name: '申报征收',
      comment: '申报征收',
      parentId: 1,
      sort: null,
      nodeType: 1,
      formId: null,
      indicatorNum: 0,
      child: [
        {
          id: 367,
          name: '申报表1',
          comment: '申报表1',
          parentId: 48,
          sort: null,
          nodeType: 2,
          formId: 315,
          indicatorNum: 4,
          child: null,
          indicatorVOList: null,
        },
        {
          id: 99,
          name: '测试数据',
          comment: '测试数据',
          parentId: 48,
          sort: null,
          nodeType: 1,
          formId: null,
          indicatorNum: 0,
          child: null,
          indicatorVOList: null,
        },
      ],
      indicatorVOList: null,
    },
    {
      id: 47,
      name: '登记认定',
      comment: '登记认定',
      parentId: 1,
      sort: null,
      nodeType: 1,
      formId: null,
      indicatorNum: 0,
      child: [
        {
          id: 83,
          name: '登记',
          comment: '登记',
          parentId: 47,
          sort: null,
          nodeType: 1,
          formId: null,
          indicatorNum: 0,
          child: null,
          indicatorVOList: null,
        },
        {
          id: 67,
          name: '认定',
          comment: '认定',
          parentId: 47,
          sort: null,
          nodeType: 1,
          formId: null,
          indicatorNum: 0,
          child: null,
          indicatorVOList: null,
        },
      ],
      indicatorVOList: null,
    },
  ],
  indicatorVOList: null,
};

export default data;
